hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2df4615c3f5ac698e96bdf6eb75d942135d4d8cf914c611ad802956b4d7c1edc"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "a22428140ae8ade420e9708a85cff2bc1a67d31d085f7521e3b0d440cc6b95a7"
metafile = true

[[files]]
file = "mods/authshield.pw.toml"
hash = "140a7384b5edd8d8ee74f69e1e83309c68df51a4091671a543b9cb516069a1ca"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "c50696cd98b02ba03425574c7850443f5cba8e097af4b6ae1c8b42bd5316a8eb"
metafile = true

[[files]]
file = "mods/cat_jam.pw.toml"
hash = "c5adc29c7b5aa88587ab54f39d654216bb087e767727a182a4bf44f98228ba5c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "4d9264c9550ed32948bd6ea78cb53ba80dd01da8e6c10fa8de4fa52c1bff4d8d"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "80a2e123c8316368eb2101baaf71a521e497046ef461a8157748c931505c4303"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "8027f1e38b07a509691bccf2a8c2d35aa069530eb1ebb11adbaed50319c05f44"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "097a2a9f31c3cccc019c63e412e6dd7d561e133a0c9117a7b32fdae11579fd56"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "d901f874a1e09747b8d0d072c38c426eceead1f29c8ba36680f8f0082996b152"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "98f1f22a846713d35b2375d4a88b18836e11f427734527d729dc1b89e7fb4da3"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "482da6b94b7a583b970e15ee78810ad48ba3983cb306d3e305b5dc6b205965c4"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "79199cff90909b0dece144138419fa205c3723d606ef0d18c2981e2f2b598d84"
metafile = true

[[files]]
file = "mods/create-trading-floor.pw.toml"
hash = "98c492446a44d3fd82fb448527dada7a496c8bc42f84a90e302e11dd34f08ba7"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "7f25446123f66f57e7cc8e148155a3da39d85b31963c663b5b9be77fc1bacbe6"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "55d8b05d23120a823f9c25322722c47e6d30f18ecafce32c295cbf55b8d55ce0"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "e7bbad3e030af9a9d0bbc35f62ede52fff316f8bc2d67f86853a9ab338065e07"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "778c42263b2ba7c9e73553bdcd70f48a3e485ba52b6a83474160d48be696b71f"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "08196e1229f323cc1eaf5969b93111705e8302a02d2acf134956f735f69e02c4"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6b5fa0d3a684cf6cf33f1399c2b4bdbee34dbe362548808315b488ac172e2ada"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "2355aae21dc167cf3af34b83ed642b23b314eeea825ed56705467e2548b2ba4e"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48d8d1f04f68dc8e6cac4ed4768790fa7ab35ee23c2aaed5391d862c6043eab"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "da9fbdce468fbfa6bd5a7ceb15465780e3e8fda9535d16f40a81343621e627a7"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2741b6724a6c7d625c1c9e647a8d20ab89cd4a3975c18706da30771754c00510"
metafile = true

[[files]]
file = "mods/fastboot.pw.toml"
hash = "9ecbea3080b9c5c9927aa7c2933c868ac6f75fdcabce905e704d427312fea8ff"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "574e4be5a4194cf6a44a5d064e3734dfbaac911c3caebfdf722ed7c35ff5215e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/full-brightness-toggle.pw.toml"
hash = "26569c9601e7490fff75ed2f556badced7f25177bebd4fad0c8789f386a4672a"
metafile = true

[[files]]
file = "mods/grieflogger.pw.toml"
hash = "a08327e2c0e9d585ef5d94571edfe0a1bb6019cb966f97c3d0fdded8e9d5c7b1"
metafile = true

[[files]]
file = "mods/gui-clock.pw.toml"
hash = "408033a936dfe6f531a14d798d3e956f536285589c7c7f78b6fda6165fcb4a1d"
metafile = true

[[files]]
file = "mods/health-indicators.pw.toml"
hash = "ae726e8dbffc7aac5d3659833d97a0a95a311f4a590e3916cf8301ea8983baa9"
metafile = true

[[files]]
file = "mods/held-item-info-neoforge.pw.toml"
hash = "e381614dc48bb664b1fd1765ae69ec4ee05babad8b847fe1a1b6bb8fd2180fcc"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/immersive-ui.pw.toml"
hash = "4a5e7ba2003a7c5df99905c4952c43e011f7b29a7fad9e20457a76a72e92fde2"
metafile = true

[[files]]
file = "mods/inv-view-forge.pw.toml"
hash = "a40e68d8848a871a5d53ebbc5c73db8cc1dfe76273a6bcef2a0e0d4d8b9299d8"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "810d40ac27fd949d2e1b6202485d646445ae2230b2a29de1b9162519217ed152"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "f565820169e3cd71f18fd0b18eab2405bc400668813d04f3f3eb75b6c8924bcc"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/languagereloadunofficial.pw.toml"
hash = "76b766b465351c6f1f57bbf68f72b66a59655d2e9a150c79b3f691d79ccbe1de"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "3f907a8532b4ca98390055ca0cb1bbd87e8ebcd44be6afe9b69280859ff37035"
metafile = true

[[files]]
file = "mods/longer-chat-history.pw.toml"
hash = "12e4601519ca5fb940e9658b71f2218f2a06c41847b714978e1568435688858d"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a9593968393bae08257ba9aae887ad60fc49991f676b637006b2bcd89907f09a"
metafile = true

[[files]]
file = "mods/neoculus.pw.toml"
hash = "dcbf1db7e42ada5710cb150588551e95fc01ecda5ada55efce4168a702f17222"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "0f095c1c6f439da9e865d86f0d798e85a82ab34e915861e5591ac47b56312de8"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
hash = "f6e94d70c2ae2aac6efa1c6c4bd5d4c8fc4dfbc180ef90fe186c79a821fa432a"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "a52c2b505827a549dfabebd6586591910fcf6e1a62dbb27604aacc96d412d5e4"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "35c3ce4f4ce649922eb68840c493190fab4f01da30272663ecbf8012ce0fd1ca"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "152769b5dfbb92a836634e315898b23b6a555c60b6f05ddf38c00085f2b784f6"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "989b2aeb18f4004fb9b7932951de4b38ffa0fc6bf5360ac32ffe9af08391d04d"
metafile = true

[[files]]
file = "mods/reforged-accurate-block-placement.pw.toml"
hash = "480e8e885c737f0f0f8be377f02e113c9ed9d34d8aa0eaf527eede799482239c"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b78044fd79ce21750d05dc61b6aede33c4b87cdc16a26f5aff472d4f73ab623c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "a182489f5f19738fd9b93d796d9e660df95fa02273a3f55f70f36314222a40a2"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "d443ed7871b1aebdcac6d3b9212676c576e6c4d86ba0eb03ddd85349f12a74e1"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "eaf856a42e2afd5a97d67d0358b5d0eb9f40b80b57baf01ebaed9539596a4885"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "62bd7012826fdcccf17a089055be67f87fb7335c88e73efc52bc9e51a1bf3188"
metafile = true

[[files]]
file = "mods/villager-in-a-bucket.pw.toml"
hash = "3e9c8727137b1c6fc3417153ade02c9a02dce16a6f91440cbf38a610af2f8654"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "edf03cb149013a97763f0a06e55733a34ab0ef0f69207554fcfc2e48abf4add8"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "9ce52d07c0c3d146a2a44f8bc187138ce7a5558a4e3ab540c86234702b6de274"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "resourcepacks/all-ore-borders.pw.toml"
hash = "0effa5b24566003cc58d0d711c189fc8a0f4c2b395bd380c3e4f121518175841"
metafile = true

[[files]]
file = "resourcepacks/better-small-shield.pw.toml"
hash = "c117d347c724130a913a213f4c4f52211af69edcd09dbf52297a509b081b53f9"
metafile = true

[[files]]
file = "resourcepacks/crop-growth-indicator.pw.toml"
hash = "e810f9e80ea35b5c9e5ccca36559d75fb4bc5aa31be26a88da43382025db736c"
metafile = true

[[files]]
file = "resourcepacks/crosshair-v3.pw.toml"
hash = "57a4ea26995ef4f58dac79426cf67a1bef23f2223591813bcdbcb930537a361f"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "resourcepacks/waxed-icons-indicator.pw.toml"
hash = "c563e205b9753cc9d01712ea39a37889e690bd753ee31f078944940102b9eca1"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "71e317f0a005cf96c85d2a917c59f166adf2c9e027ed2ea7fe5fcd2686577965"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "25183d9bf95c204041e09bec06b92a47647858b4c5d32b8b159babae60b0c9a1"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "0a3f01f56afd065dc65dffb073b4fc5f9ae031aaef08d95d9df92e0093ac8504"
metafile = true
